### ISSUE TITLE
Some items don't show their attributes in equipment lists

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#943] opened 2020-11-03 12:23 UTC
The user reported this issue with the Life Buoy item, which is from the Armoire.

![image](https://user-images.githubusercontent.com/8144640/97984908-57003800-1dcf-11eb-8eaa-2c1d2e40dbe1.png)

iOS Version: 13.5.1
Device: iPhone 8
App Version: 3.0.3 (520)
User ID: 16a4dc06-2005-4644-856b-97c3657f2d1e
Level: 87
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 0

**Comment by saraolson** [comment] 2020-11-04 21:05
hm strange, it also seems like the text isnt aligning right compared to other items.... like the item name is too high up and too far from the description...

**Comment by juanj** [comment] 2020-11-05 15:59
It looks like the stack view containing the stats labels is not resizing correctly. Some times the width is 0, and some times the stack view just disappears.

| Stack view disappeared | Stack view width 0 | 
|---|---|
| ![Screen Shot 2020-11-05 at 9 45 13 AM](https://user-images.githubusercontent.com/1958175/98262415-9788be80-1f53-11eb-9e20-125ddd7d0ba2.png) |  ![Screen Shot 2020-11-05 at 9 57 58 AM](https://user-images.githubusercontent.com/1958175/98262431-99eb1880-1f53-11eb-9fe3-1e39b014f408.png) | 

So far I haven't been able to find what is causing this, but from debugging the view, I can say that this don't look like a problem with the labels being hidden. They appear on the inspector but with a width of 0.

This is not 100% reproducible, but is close to it. After scrolling the table view a number of times it happens. But after the problematic cell is reused most of the time it fixes itself.

**Comment by saraolson** [comment] 2024-06-13 20:52
it seems like this is fixed in 3.10. im unable to reproduce. can reopen if anyone encounters it again.

**Closed as completed by saraolson** 2024-06-13 20:52 UTC
Labels: Type: Bug, Help wanted, Priority: minor
