### ISSUE TITLE
Reminder notifications for dailies does not work

### ISSUE THREAD

**Issue by asgeir-s** [HabitRPG/habitrpg-ios#756] opened 2018-10-17 11:10 UTC
After setting a reminder for a daily task no notification is received. Only reminders for To-Dos are working.

It is also not possible to remove reminders from a task (only adding and editing works).

**Comment by spageetman** [comment] 2018-12-11 01:36
Hey I’ve been using Habitica for a couple of days and I’m really annoyed that this is happening reminders are pretty important to help me keep on task (ADHD ) and I can see from all the issue reports your busy but this is a pretty important feature and it doesn’t even have a label pls at least give it a look and also I can delete the reminders

**Comment by phillipthelen** [comment] 2018-12-11 06:39
I have been looking into this, however so far I have not found a way to reproduce it. Which makes it hard to fix it, since I can‘t tell what is causing the issue. Are you receiving other notifications like the daily checkin one? And are the tasks that should have reminders displayed as active (not gray) in the app?

Do you mean you can‘t delete reminders?

**Comment by spageetman** [comment] 2018-12-11 08:26
I am getting to-do and daily checkin notifications the tasks are active and do nothing out of the ordinary and I mean filters as in (school, work ect.) I can’t delete them I also can’t swipe left to delete tasks a little grey no smoking simbol with out the cigarette like a circle with a diagonal line through it thanks for acknowledging this so quick and let me know if I can help (I can’t code but I signed up for some sort of school as recommend by one of the peeps on the guild and am about to learn the basics)

**Comment by phillipthelen** [comment] 2018-12-11 11:44
Thanks for the additional info!
What happens when you try to delete a reminder? I just tested it and it works well for me.
You can also delete tasks by opening up the task edit form and then tapping delete at the bottom.

To further look into the reminders issue, it would be useful if I could take a look at the task data you have. (not at the actual task text, but just the "metadata" like the interval configuration and reminders, so no personal information) For that, I need your habitica UserID (you can find that in the API settings), or your habitica @ username.

**Comment by spageetman** [comment] 2018-12-13 03:51
Sorry I thought I sent a reply but it didn’t go through 
User Id: 926ad0f8-581f-4f92-82d9-76311c325802

**Comment by saraolson** [comment] 2019-02-21 16:56
@spageetman @sogasg is this still happening for you? i've been getting my reminders consistently and am able to delete them by tapping the 'x' by them in the task edit screen.

**Comment by spageetman** [comment] 2019-02-22 23:00
My phone died from water and haven't been able to go back on I also have android now so idk

**Comment by saraolson** [comment] 2020-01-08 16:38
We believe this is fixed now, closing until we hear otherwise

**Closed as completed by saraolson** 2020-01-08 16:38 UTC
