### ISSUE TITLE
Challenges: categories text is styled wrong

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#584] opened 2018-02-03 23:26 UTC
the text for categories looks very technical right now ie: "habitica_official" instead of "Habitica Official"

**Comment by phillipthelen** [comment] 2018-02-05 09:18
Main issue with this is that the data the API returns isn't correct for this. The challenge objects have a "slug" and "name" field, however both are the same string (in this case "habitica_official"). imho this should be looked at/fixed on the api, since it doesn't seem to work as intended right now

**Comment by schrockblock** [comment] 2018-02-27 23:41
Looks like @SabreCat is taking care of this server-side. Closing here.

**Closed as completed by schrockblock** 2018-02-27 23:41 UTC
Labels: Type: Bug, Priority: medium
