### ISSUE TITLE
Build input cannot be found: /.../Generated/Secrets.swift

### ISSUE THREAD

**Issue by diyoyo** [HabitRPG/habitrpg-ios#1334] opened 2024-05-27 13:04 UTC
Hi, 
I'm trying to build the app but XCode is against me on this.
Here are the changes I made so far, to be able to reach the build phase:
- changed Bundle Name
- changed group name
- generated signing confs for the Bundle (using free account)
- removed all the add-ons like Siri, Sign-In etc. (because of free account)

Now, I'm stuck at :
```
Build input file cannot be found: '/.../habitica-ios/HabitRPG/Generated/Secrets.swift'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?
```

Any idea why?

PS: maybe Firebase or Amplitude? How can I disable it for now?

**Comment by diyoyo** [comment] 2024-05-27 13:38
Ok, actually, I solved this and got it to build:

- copied `secrets.yml.example` to `secrets.yml`
- In **Build Phases**->**Run SwiftGen** , added `secrets.yml` in the input files
- Made sure I had `swiftgen` installed on my Mac with `brew install swiftgen` 

Now I guess, I'm stuck at the same point as the others folks here [https://github.com/HabitRPG/habitica-ios/issues/873](url)

Even after changing `debug.xcconfig`, I cannot test the self-hosted option (even with SSL certificate from Let'sEncrypt)

**Comment by phillipthelen** [comment] 2024-05-27 16:00
Closing this, since the issue is resolved.
I'm not sure what you mean with being stuck as the others since people seem to have been running into this issue. Discussion relating that should probably continue in the linked issue.

**Closed as completed by phillipthelen** 2024-05-27 16:00 UTC

**Comment by diyoyo** [comment] 2024-05-27 20:16
> Closing this, since the issue is resolved. I'm not sure what you mean with being stuck as the others since people seem to have been running into this issue. Discussion relating that should probably continue in the linked issue.

just for the sake of clarification: I meant that other people in the shared link mentioned being able to build but not being able to connect to a self-hosted server. That's my definition of "being stuck", since their goal is not reached. You're right in that it is not related to the 'Secrets' problem, and thus I thank you very much for taking the time to clean the clutter I was starting with this newly open issue.
FYI, I'm not 'stuck' anymore, I've reached my goal of compiling everything to be able to run on self-hosted server, even with the personal constraint that my Apple developer's subscription has ended a while ago already.
I will post a more detailed guideline in isse #873 but you may think (I do, actually) that this will still be off-topic. Indeed, as far as I understand, the goal of #873 is to integrate the choice of the server in the UI, in the official app served through the App Store. I won't solve this, but I have enough time to write a tutorial to explain how to use your workaround `debug.xcconfig` to beginners.

(PS: btw, the path is outdated in the headers of `debug.xcconfig` sample file)
