### ISSUE TITLE
Onboarding Tasks not properly rewarding finishing all tasks

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#989] opened 2021-03-14 14:36 UTC
> I play on an iPhone 11 / iOS 14.4. I previously had an account from ages ago but reinstalled the app yesterday and started over.
> 
> I could see the onboarding quest at the top of the menu then an app update came out today and since then whenever I open the menu the onboarding tasks appears briefly then vanishes at the top. 
> 
> I completed the final 5/5 task afterwards for the reward and selected “View Onboarding tasks” on the congratulations pop up hoping to claim the reward but it does not load. 
> 
> Due to this bug I cannot claim the 100 gold starter reward. Attached is a screenshot of the menu where it usually appeared at the top of. 
> 
> This started on version 3.2.1 (572).

Reports that their girlfriend (on the same version) has the same issue at 4/5 tasks completed.

-------

Confirmed that the app is not automatically rewarding finishing all tasks. The final modal isnt displaying and gold is not being given out, but the onboarding UI disappears from the menu as it should when you're finished. (haven't been able to replicate other issues with the hub/ui not showing or only showing briefly, but maybe fixing one issue will fix that) -sara

**Comment by saraolson** [comment] 2021-03-16 15:22
hm, the reward shouldn't need to be claimed. it should be automatic after you complete 5/5. the 'view onboarding tasks' button only appears on the individual congratulations modals for each task. maybe the final modal isnt displaying as it should, or maybe they havent done them all since they can't view the hub screen? will test myself later today. 

<img width="858" alt="Screen Shot 2021-03-16 at 11 20 57 AM" src="https://user-images.githubusercontent.com/12453119/111334208-bc9be500-8649-11eb-91c2-d089725687f0.png">

**Comment by saraolson** [comment] 2021-03-16 17:34
okay so testing this myself, i wasn't able to reproduce the onboarding ui in the menu showing briefly, but when i completed all tasks it just showed me the specific tasks modal and not the onboarding complete modal. i also wasnt awarded 100 gold automatically.

**Comment by saraolson** [comment] 2021-03-16 17:38
also wasnt able to reproduce the onboarding hub not showing either

**Comment by saraolson** [comment] 2021-03-17 16:27
the reward issue was caused by a server block, rather than something with ios. that will be fixed in tomorrow's deploy. the other issue with the guide disappearing and reappearing we couldn't reproduce. going to close this anyways and reopen if someone else reports that after tomorrows deploy

**Closed as completed by saraolson** 2021-03-17 16:27 UTC
Labels: Type: Bug
