### ISSUE TITLE
After opening menu, top bar disappears

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitrpg-ios#1022] opened 2021-06-18 13:51 UTC
"Hi. This is a bug I’ve been encountering every time on the iOS app. The three parallel lines button at the bottom right of the bar at the bottom- upon being clicked causes the top bar with the username/notifications/messages/settings to disappear from the top of the screen. If I try to scroll down to it, it simply does not appear."

![Image(1)](https://user-images.githubusercontent.com/8144640/122571434-a33d7700-d044-11eb-94de-167ad41ce403.png)

They're on version 3.3(595).

**Comment by saraolson** [comment] 2021-07-01 19:52
this was an issue thats caused by the summer event starting, but thee app not correctly updating the menu to show the seasonal shop. force closing the app and reopening so the menu loads the shop correctly in 3.3 fixes it. however, we fixed the event start issue in 3.3.1 so this should no longer be a problem.

**Closed as completed by saraolson** 2021-07-01 19:52 UTC
Labels: Type: Bug
