### ISSUE TITLE
Support for markdown links

### ISSUE THREAD

**Issue by davidkazuhiro** [HabitRPG/habitrpg-ios#485] opened 2017-09-25 00:36 UTC
Currently, markdown hyperlinks are not rendered in the iOS app

For example 
```[Habitica](https://habitica.com/)```

should be displayed as

> [Habitica](https://habitica.com/)

But instead it just displays as 

> ```[Habitica](https://habitica.com/)```

This is true for the following fields:
- [ ] Titles
- [ ] Extra Notes
- [ ] Checklist items

**Comment by phillipthelen** [comment] 2017-09-26 13:00
This is a duplicate of #85

**Closed as completed** 2017-09-26 13:00 UTC
