### ISSUE TITLE
Reset password toast disappears too fast

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitrpg-ios#560] opened 2018-01-08 20:17 UTC
When you reset your password, you get a toast with a long, tiny text sentence thats impossible to read in time.

Ideally i'd like to change the string to something more concise, but also potentially making it stay on the screen for longer if thats possible to do only to specific toasts.

**Comment by phillipthelen** [comment] 2018-07-26 07:39
A good fix for this would be to add an optional "duration" parameter to the `ToastView` class, that is then used by the `ToastManager` class when displaying. That way we can choose to display some messages longer than others.

**Comment by JStanger13** [comment] 2018-07-27 16:09
I wanna take this one on!

**Comment by JStanger13** [comment] 2018-07-27 16:55
Is there a toast when clicking on "Change" in the "showPasswordChangeAlert?" When I change my password in the app, nothing happens to confirm weather or not my password changed, and I don't see a ToastManager or anything in the "showPasswordChangeAlert" function.  Is the issue that it's too fast or that there isn't a toast at all?

**Comment by Alys** [comment] 2018-07-27 22:21
Is this issue referring to the message you see from the "forgot password" form after you've entered your email address and clicked the submit button? If so, the way the message is handled on the website and Android app is that it stays on screen until you click an "OK" button. That would be better than a toast because it's important that the user does read the message.

**Comment by JStanger13** [comment] 2018-07-27 22:28
I think I got it! There's a "Forgot Password" and "Reset Password." I think the issue is in "Forgot Password" when you log in. "Reset Password" is in the menu settings.

**Comment by Alys** [comment] 2018-11-29 10:08
@JStanger13 I've just noticed that you sent me a message in Facebook about this back in August. I don't visit Facebook often, and Facebook makes messages from new contacts difficult to notice. If you still want to work on this and still have questions about it, you can post them here. Note that other changes since then might have made this issue redundant so it would be best to post  here even if you don't have questions to see if staff still want a fix made.

**Comment by spageetman** [comment] 2018-12-11 01:43
No the message still gos too fast

**Closed as completed** 2019-03-22 14:19 UTC
Labels: Type: Enhancement, Good first issue, Help wanted, Priority: medium
